/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.yefrig.practica1estructuradedatos.frame;

import com.yefrig.practica1estructuradedatos.listaEnlazada.ListaEnlazadaDoble;
import com.yefrig.practica1estructuradedatos.listaEnlazada.Apuesta;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author yefri
 */
public class VentanaPrincipalJframe extends javax.swing.JFrame {

    private Apuesta[] apuestas;
    private static ListaEnlazadaDoble listaDoble;
    private IngresoResultadosJFrame ingreso;

    /**
     * Creates new form VentanaPrincipalJframe
     */
    File archivo;

    public static ListaEnlazadaDoble getListaDoble() {
        return listaDoble;
    }

    public static void setListaDoble(ListaEnlazadaDoble listaDoble) {
        VentanaPrincipalJframe.listaDoble = listaDoble;
    }

    public VentanaPrincipalJframe() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.verficarApuestasButton.setEnabled(false);
        this.ingresarResultadosButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaCargaTextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        cargaArchivoButton = new javax.swing.JButton();
        verficarApuestasButton = new javax.swing.JButton();
        jButtonNuevaCarrera = new javax.swing.JButton();
        ingresarApuestasButton = new javax.swing.JButton();
        ingresarResultadosButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Control de Hipodromo");

        areaCargaTextArea.setColumns(20);
        areaCargaTextArea.setRows(5);
        jScrollPane1.setViewportView(areaCargaTextArea);

        cargaArchivoButton.setText("Cargar Archivo");
        cargaArchivoButton.setPreferredSize(new java.awt.Dimension(133, 35));
        cargaArchivoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargaArchivoButtonActionPerformed(evt);
            }
        });

        verficarApuestasButton.setText("Verificar Apuestas");
        verficarApuestasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verficarApuestasButtonActionPerformed(evt);
            }
        });

        jButtonNuevaCarrera.setText("Nueva Carrera");
        jButtonNuevaCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaCarreraActionPerformed(evt);
            }
        });

        ingresarApuestasButton.setText("Ingresar Apuestas");
        ingresarApuestasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarApuestasButtonActionPerformed(evt);
            }
        });

        ingresarResultadosButton.setText("Ingresar Resultados");
        ingresarResultadosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarResultadosButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cargaArchivoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(ingresarApuestasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(verficarApuestasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtonNuevaCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(ingresarResultadosButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ingresarResultadosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonNuevaCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(verficarApuestasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cargaArchivoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ingresarApuestasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargaArchivoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaArchivoButtonActionPerformed
        cargarArchivo();
    }//GEN-LAST:event_cargaArchivoButtonActionPerformed

    private void ingresarApuestasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarApuestasButtonActionPerformed
        if (!areaCargaTextArea.getText().equals("")) {
            lecturaTexto();
        }

    }//GEN-LAST:event_ingresarApuestasButtonActionPerformed

    private void jButtonNuevaCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaCarreraActionPerformed
        if (!this.areaCargaTextArea.getText().equals("")) {
            int opcion = JOptionPane.showConfirmDialog(null, "¿Desea eliminar la carrera actual y crear una nueva?");
            if (opcion == 0) {
                this.areaCargaTextArea.setText("");
                this.cargaArchivoButton.setEnabled(true);
                this.ingresarApuestasButton.setEnabled(true);
                this.verficarApuestasButton.setEnabled(true);
            }

        }

    }//GEN-LAST:event_jButtonNuevaCarreraActionPerformed

    private void verficarApuestasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verficarApuestasButtonActionPerformed
        listaDoble.cabeza();
        System.out.println("------------------------------------");
        listaDoble.crearArchivoEliminados();
        this.verficarApuestasButton.setEnabled(false);
        this.ingresarResultadosButton.setEnabled(true);
        this.areaCargaTextArea.setText("");
        this.areaCargaTextArea.append("Apuestas aceptadas\n");
        listaDoble.imprimirApuestas();
    }//GEN-LAST:event_verficarApuestasButtonActionPerformed

    private void ingresarResultadosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarResultadosButtonActionPerformed
        ingreso = new IngresoResultadosJFrame(listaDoble);
        ingreso.setVisible(true);
    }//GEN-LAST:event_ingresarResultadosButtonActionPerformed

    /**
     * Metodo para cargar archivo por medio de JfileCHooser lee un archivo texto
     */
    public void cargarArchivo() {
        JFileChooser ventanaCarga = new JFileChooser();
        int num = ventanaCarga.showOpenDialog(this);
        if (num == JFileChooser.APPROVE_OPTION) {
            this.areaCargaTextArea.setText("");
            String linea;
            try {
                archivo = ventanaCarga.getSelectedFile();
                FileReader fileReader = new FileReader(archivo);
                BufferedReader texto = new BufferedReader(fileReader);
                while ((linea = texto.readLine()) != null) {
                    areaCargaTextArea.append(linea + "\n");
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error al leer Archivo");
            }
        }
    }

    private void lecturaTexto() {
        int num = areaCargaTextArea.getLineCount()+1;
        apuestas = new Apuesta[num];
        String[] lineas = areaCargaTextArea.getText().split("\n");
        for (int i = 0; i < lineas.length; i++) {
            if (lineas[i] != null) {
                String[] campos = lineas[i].split(",");
                if (campos.length == 12) {
                    int num1, num2, num3, num4, num5, num6, num7, num8, num9, num10;
                    double monto;
                    int[] ordenApuesta;
                    try {
                        num1 = Integer.valueOf(campos[2]);
                        num2 = Integer.valueOf(campos[3]);
                        num3 = Integer.valueOf(campos[4]);
                        num4 = Integer.valueOf(campos[5]);
                        num5 = Integer.valueOf(campos[6]);
                        num6 = Integer.valueOf(campos[7]);
                        num7 = Integer.valueOf(campos[8]);
                        num8 = Integer.valueOf(campos[9]);
                        num9 = Integer.valueOf(campos[10]);
                        num10 = Integer.valueOf(campos[11]);
                        monto = Double.parseDouble(campos[1]);
                        ordenApuesta = new int[]{num1, num2, num3, num4, num5, num6, num7, num8, num9, num10};
                        apuestas[i] = new Apuesta(campos[0], monto, ordenApuesta);
                    } catch (Exception e) {
                        System.out.println("Formato de numero  incorrecto: " + e);
                    }
                }
            }

        }
        ingresoApuestas();
    }

    private void ingresoApuestas() {
        listaDoble = new ListaEnlazadaDoble();
        try {
            for (int i = 0; i < apuestas.length; i++) {
                if (apuestas[i] != null) {
                    listaDoble.agregarAlFinal(apuestas[i]);
                }
            }
            this.ingresarApuestasButton.setEnabled(false);
            this.verficarApuestasButton.setEnabled(true);
        } catch (Exception e) {
            System.out.println(e);
        }
        this.areaCargaTextArea.setEditable(false);
        this.cargaArchivoButton.setEnabled(false);
        JOptionPane.showMessageDialog(null, "Apuestas Ingresadas");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea areaCargaTextArea;
    private javax.swing.JButton cargaArchivoButton;
    private javax.swing.JButton ingresarApuestasButton;
    public static javax.swing.JButton ingresarResultadosButton;
    private javax.swing.JButton jButtonNuevaCarrera;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton verficarApuestasButton;
    // End of variables declaration//GEN-END:variables
}
